---
- debug: 
    msg: "DeProvision AWS Env"

- name: Get All OpenShift all-in-one instances  
  ec2_instance_facts:
    region: "{{aws.region}}"
    aws_access_key: "{{aws.access_key}}"
    aws_secret_key: "{{aws.secret_key}}"
    filters: 
      "tag:Name": "{{instance_name}}"
  register: instances

- name: AWS Delete All in one OpenShift Node
  ec2:
    region: "{{aws.region}}"
    aws_access_key: "{{aws.access_key}}"
    aws_secret_key: "{{aws.secret_key}}"
    instance_ids: "{{item.instance_id}}"
    state: absent
  with_items: "{{instances.instances}}"
  tags: 
    - rollback
    - cloud-aws

# Query and delete VPC Resources

- name: AWS Query OpenShift VPC 
  ec2_vpc_net_facts:
    region: "{{aws.region}}"
    aws_access_key: "{{aws.access_key}}"
    aws_secret_key: "{{aws.secret_key}}"
    filters:
      "tag:Name": 'openshift-vpc'
  tags:
    - rollback
    - cloud-aws
  register: ec2vpc 

- name: AWS Set VPC ID to Local Variable
  set_fact:
    vpc_id: "{{ec2vpc.vpcs[0].id}}"
  tags:
    - rollback
    - cloud-aws
  when: ( ec2vpc.vpcs | list | length > 0)

# TODO How to delete VPC with Depndencies ??
- name: Delete VPC
  ec2_vpc_net:
    name: openshift-vpc
    region: "{{aws.region}}"
    aws_access_key: "{{aws.access_key}}"
    aws_secret_key: "{{aws.secret_key}}"
    cidr_block: '10.10.0.0/16'
    state: absent
  ignore_errors: True
  when: vpc_id is defined
  tags:
    - rollback
    - cloud-aws

- name: "EC2 Delete ec2 key pair {{aws.key_pair_name}}"
  ec2_key:
    name: "{{aws.key_pair_name}}"
    region: "{{aws.region}}"
    aws_access_key: "{{aws.access_key}}"
    aws_secret_key: "{{aws.secret_key}}"
    state: absent
  tags: 
    - rollback
    - cloud-aws