---
- debug: 
    msg: "DeProvision Azure Env"

- name: Azure Delete OpenShift resource group
  azure_rm_resourcegroup:
      name: OpenShift
      client_id: "{{azr.client_id}}"
      secret: "{{azr.secret}}"
      subscription_id: "{{azr.subscription_id}}"
      tenant: "{{azr.tenant}}"
      location: "{{azr.location}}" 
      force: yes
      state: absent
  tags:
    - cloud-azr
    - rollback