---
- name: Its Azure Env
  debug: 
    msg: "Provision Azure Env"

#############################################################################
## Resource Group
#############################################################################

- name: Azure Create a resource group
  azure_rm_resourcegroup:
    name: "{{azr.resource_group}}"
    client_id: "{{azr.client_id}}"
    secret: "{{azr.secret}}"
    subscription_id: "{{azr.subscription_id}}"
    tenant: "{{azr.tenant}}"
    location: "{{azr.location}}" 
    tags:
        name: openshift-all-in-one
  register:
     azr_rm_resource_group
  tags:
    - cloud-azr

#############################################################################
## Security Group
#############################################################################

- name: Azure Create OpenShift Network Security Group
  azure_rm_securitygroup:
    name: "{{azr.security_group}}"
    client_id: "{{azr.client_id}}"
    secret: "{{azr.secret}}"
    subscription_id: "{{azr.subscription_id}}"
    tenant: "{{azr.tenant}}"
    location: "{{azr.location}}" 
    resource_group: "{{azr.resource_group}}"
    rules: 
        - name: 'allow-ssh'
          description: "Allowing SSH"
          priority: 100
          destination_port_range: 22
          access: Allow
        - name: 'allow-http'
          description: "Allowing HTTP"
          priority: 101
          destination_port_range: 80
          access: Allow
        - name: 'allow-https'
          description: "Allowing HTTPS"
          priority: 102
          destination_port_range: 443
          access: Allow
        - name: 'allow-openshift-master-console'
          description: "Allowing OpenShift Master Console"
          priority: 103
          destination_port_range: 8443
          access: Allow
    tags:
        name: openshift-all-in-one
  register:
     azr_rm_nsg
  tags:
    - cloud-azr

#############################################################################
## VPC Network
#############################################################################
- name: Azure Create OpenShift Network
  azure_rm_virtualnetwork:
    name: "{{azr.vm_net_name}}"
    client_id: "{{azr.client_id}}"
    secret: "{{azr.secret}}"
    subscription_id: "{{azr.subscription_id}}"
    tenant: "{{azr.tenant}}"
    location: "{{azr.location}}"
    resource_group: "{{azr.resource_group}}"
    address_prefixes_cidr:
    - 192.168.0.0/16       
    tags:
        name: openshift-all-in-one
  register:
     azr_rm_vnet
  tags:
    - cloud-azr

- name: Azure Create OpenShift Network Subnet
  azure_rm_subnet:
    name: openshift-subnet-01
    virtual_network_name: "{{azr.vm_net_name}}"
    client_id: "{{azr.client_id}}"
    secret: "{{azr.secret}}"
    subscription_id: "{{azr.subscription_id}}"
    tenant: "{{azr.tenant}}"
    resource_group: "{{azr.resource_group}}"
    address_prefix_cidr: "192.168.1.0/24"
    security_group: "{{azr.security_group}}"
    tags:
        name: openshift-all-in-one
  register:
     azr_rm_vnet_subnet
  tags:
    - cloud-azr

- name: Azure Create OpenShift Default NIC
  azure_rm_networkinterface:
    name: openshift-nic01
    client_id: "{{azr.client_id}}"
    secret: "{{azr.secret}}"
    subscription_id: "{{azr.subscription_id}}"
    tenant: "{{azr.tenant}}"
    resource_group: "{{azr.resource_group}}"      
    ip_configurations:
    - name: "openshift-ip"
      public_ip_address_name: "openshift-ip"
      public_ip_allocation_method: "Static"
      primary: True
    security_group: "{{azr.security_group}}"
    subnet_name: openshift-subnet-01    
    virtual_network: "{{azr.vm_net_name}}"
    tags:
        name: openshift-all-in-one  
  register:
    azr_rm_nic01
  tags:
    - cloud-azr

#############################################################################
## Compute
#############################################################################

- name: Azure Create All In One OpenShift Node
  azure_rm_virtualmachine:
    name: "{{instance_name}}"
    client_id: "{{azr.client_id}}"
    secret: "{{azr.secret}}"
    subscription_id: "{{azr.subscription_id}}"
    tenant: "{{azr.tenant}}"
    location: "{{azr.location}}"      
    resource_group: "{{azr.resource_group}}"
    ssh_password_enabled: False
    managed_disk_type: Standard_LRS
    data_disks: 
    - lun: 0
      managed_disk_type: "Standard_LRS"
      disk_size_gb: 128
      storage_blob_name: "{{instance_name}}-docker"
    ssh_public_keys: 
    - key_data: "{{azr.public_key_file}}"
      path: "/home/{{azr.cloud_user}}/.ssh/authorized_keys"
    vm_size: "{{azr.vm_size}}"      
    admin_username: "{{azr.cloud_user}}"
    image: "{{azr.image}}"
    network_interface_names:
    - openshift-nic01
    tags:
      name: openshift-all-in-one 
  register:
     azr_rm_vm

- name: Azure Public IP Query Fact
  set_fact:
    public_ip_query: "networkProfile.networkInterfaces[?name == 'openshift-nic01'].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress"

- name: Azure Set VM Facts
  set_fact:   
    public_ip: "{{azr_rm_vm.ansible_facts.azure_vm.properties|json_query(public_ip_query)|first}}" 

- debug: 
    msg: "Azure OpenShift Node Details IP {{public_ip}}"
  tags:
    - cloud-azr

- name: azure wait for ssh
  wait_for:
    delay: "1"
    host: "{{ public_ip }}"
    port: "22"
    state: started
    timeout: "120"
  tags:
    - cloud-azr

#############################################################################
## Write to inventory
##############################################################################

- name: Azure Build VM Hosts
  add_host:
    name: "azr-openshift"
    ansible_ssh_host: "{{public_ip}}"
    ansible_ssh_user: "{{azr.cloud_user}}"
    ansible_ssh_private_key_file: "{{azr.private_key_file}}"
  tags:
    - cloud-azr

- name: Setup Cloud Inventory Tasks
  include_tasks: cloud_inventory.yaml
  vars:
    cloud_host: "{{ public_ip }}"
    cloud_user: "{{ azr.cloud_user}}"
    private_key_file: "{{azr.private_key_file}}"
    cloud_host_alias: "azr-openshift"
    cloud_provider: "azr"
    is_rhel: "{{azr.image.offer == 'RHEL'}}"
    hybricloud_inventory_dir: "{{hybridcloud_distro_base_dir}}/azr/inventory"
    hybridcloud_distro_dir: "{{hybridcloud_distro_base_dir}}/azr"
  tags:
    - cloud-azr
